.PHONY: run
run:
	@go run ./cmd/example-provider-api/main.go --config="./cmd/example-provider-api/configuration.yaml"

.PHONY: build
build:
	@go build ./cmd/example-provider-api/main.go

.PHONY: test
test:
	@go test -v -cover ./.../